### ISSUE TITLE
Error page rendered instead of the expected home screen

### ISSUE THREAD

**Issue by tMaxx** [marzeq/xbox-cloud-gaming-electron#1]
### What and where

This line will not resolve the page correctly if you're outside of the english-speaking world, and may result in an error page being displayed instead:

https://github.com/marzeq/xbox-cloud-gaming-electron/blob/8345cf9c52145a6f677530a65a64d9db5dc84001/src/main.ts#L41

### Details

If the `app.getLocale()` returns `pl`, as it is in my case, the URL will resolve to:
```https://www.xbox.com/pl/play```
which then will get auto-redirected to
```https://www.xbox.com/en-GB/pl/play```
as the Xbox website doesn't recognize the shortened locale/market string. The `/en-GB/pl/play` renders an error page.

Correct URL for `pl` locale would be `https://www.xbox.com/pl-PL/play`. Chromium API won't return what Xbox website expects in many cases, as evidenced here: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/l10n/l10n_util.cc

### Solution

My proposal would be to stick to `https://www.xbox.com/play` URL, as it will auto-redirect to the correct locale.

Alternatively, you could check the locale string length, and default to `en-GB` if it's shorter than expected (trying to do some magic with guessing/reconstructing the correct string will be problematic from my overall experience).

**Comment by marzeq** [comment]
Thanks for submitting your issue!

From what I've seen, the auto detection feature when using `https://www.xbox.com/play` doesn't work that well, as I was redirected to `/en-US/play` instead of `/en-GB/play`, but I'd rather have the app working instead of it not working, so I've pushed out a quick-fix update to use `https://www.xbox.com/play` instead.

I'm going to close this issue for now.
